### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Diwann** [philips/grpc-gateway-example#12] opened 2016-11-23 12:52 UTC
I am trying to follow the tutorial here: https://coreos.com/blog/gRPC-protobufs-swagger.html 
but I have the following error: 

```
go get -u github.com/philips/grpc-gateway-example
# github.com/philips/grpc-gateway-example/echopb
echopb/service.pb.go:56: undefined: grpc.SupportPackageIsVersion3
```

Maybe same as here: https://github.com/bmeg/task-execution-server/issues/24 ?

**Comment by samuelvarley** [comment] 2016-11-26 22:18
I also came across this. The problem is that the autogenerated files are not being regenerated when you run "go get ..."; instead, it's using the files that have been checked into git. Those autogenerated files are now out of date with some other packages and it's triggering a compile-time assertion.

The instructions below assume that you are on Linux and have the $GOPATH environment variable set. You may need to do things slightly differently with other setups.

To regenerate the files, "cd" into "echopb" and type "make". You may find that you need to install some extra dependencies before that will work. 

```
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
go get -u github.com/golang/protobuf/protoc-gen-go
```

Those will produce some executables such as "protoc-gen-go". Make sure that the location of those exectables is in your $PATH environment variable. Use the following command:

```
export PATH=$PATH:$GOPATH/bin
```

You will also need "protoc" which you can download from https://github.com/google/protobuf/releases

* Copy "bin/protoc" to somewhere in your $PATH.
* Copy the "include/google" directory into "$GOPATH/src".

With all the dependencies now installed, "make" should work without producing any errors. Once you have run "make", the original "go get ..." command should run without problems.

**Comment by philips** [comment] 2016-11-29 01:22
@samuelvarley can you submit a PR to bump the compiled assests?

**Comment by samuelvarley** [comment] 2016-11-29 04:27
OK, I have made PR #13.

**Comment by philips** [comment] 2016-11-30 02:11
Merged. This should be fixed now.

**Closed by philips** 2016-11-30 02:11 UTC
